### PR TITLE
Fixes for open issues #22 and #11

### PR DESCRIPTION
**Pull request by MrStahlfelge**
Music was disposed when stopped, but not unloaded from Asset Manager and therefore disposed music could not play any more. See #22

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Also fixed issue #11

**Comment by MrStahlfelge** [comment]
@violetwolf Thanks for the approval. As I see there is some interest in this project, I pushed all my fixes to Github: https://github.com/MrStahlfelge/SMC-libgdx

**Comment by pedja1** [comment]
Merged manually.
Also merged most of the stuff from your fork @MrStahlfelge, thank you for continuing the development on this project

**Comment by MrStahlfelge** [comment]
👍 great to see you jump back on the project

**Pull request closed without merging**
